### ISSUE TITLE
something about logfile

### ISSUE THREAD

**Issue by MrMix2016** [linezero/Blog#1]
i can create log file successfully,but no word in my logfile,am i missing something
and create an Exception file
2017-01-17 13:16:13.5211 Error Error has been raised. Exception: System.TypeInitializationException: The type initializer for 'NLog.Internal.PlatformDetector' threw an exception. ---> System.MissingMethodException: Method not found: 'Microsoft.Extensions.PlatformAbstractions.RuntimeEnvironment Microsoft.Extensions.PlatformAbstractions.PlatformServices.get_Runtime()'.
   at NLog.Internal.PlatformDetector.GetCurrentRuntimeOS()
   at NLog.Internal.PlatformDetector..cctor()
   --- End of inner exception stack trace ---
   at NLog.Internal.PlatformDetector.get_CurrentOS()
   at NLog.Internal.FileAppenders.BaseFileAppender.TryCreateFileStream(Boolean allowFileSharedWriting)
   at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream(Boolean allowFileSharedWriting)
   at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write(Byte[] bytes)
   at NLog.Targets.FileTarget.WriteToFile(String fileName, LogEventInfo logEvent, Byte[] bytes, Boolean justData)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)

**Comment by linezero** [comment]
Nlog updates to the latest version.
